language: python


matrix:
  include:
    - python: 2.7
      env:
        - DJANGO=1.8

    - python: 2.7
      env:
        - DJANGO=1.11

    - python: 3.4
      env:
        - DJANGO=1.8

    - python: 3.4
      env:
        - DJANGO=1.11

    - python: 3.4
      env:
        - DJANGO=2.0

    - python: 3.5
      env:
        - DJANGO=1.8

    - python: 3.5
      env:
        - DJANGO=1.11

    - python: 3.5
      env:
        - DJANGO=2.0

    - python: 3.5
      dist: xenial
      env:
        - DJANGO=2.1

    - python: 3.6
      env:
        - DJANGO=1.8

    - python: 3.6
      env:
        - DJANGO=1.11

    - python: 3.6
      env:
        - DJANGO=2.0

    - python: 3.6
      dist: xenial
      env:
        - DJANGO=2.1

    # dist + sudo, see https://github.com/travis-ci/travis-ci/issues/9815 and
    #  https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-425720905

    - python: 3.7
      dist: xenial
      sudo: true
      env:
        - DJANGO=1.11

    - python: 3.7
      dist: xenial
      sudo: true
      env:
        - DJANGO=2.0

    - python: 3.7
      dist: xenial
      sudo: true
      env:
        - DJANGO=2.1-zeep2

    - python: 3.7
      dist: xenial
      sudo: true
      env:
        - DJANGO=2.1

install:
  - pip install tox tox-travis

script:
  - tox

deploy:
  provider: pypi
  user: thorgate
  password:
    secure: >
      Xsl/Oyo2zsQu5TEfiUZLFLFyRCq+XuLpWhfrp8UYiaNeVeolpEfe145VRBe0wNhbNqiDCm/jRkJeKzUfoNxWz4skVzAymQBk0k1ubalJXfjza
      DQS2KvqoGMWWedRWrhHKkagv/wUWn6rLt61FwbWl2rLTRYZl6/i0wGsuKys+wRoLvHo0ZVH3VXyTxaO1jd4EaUwA8gcTYLoEBWJ/O9352OdSh
      83yvcHiqnbJWRVSvdjD+fK3Z5ZtG9mtgf0IEjVur/W7sHdZ060hanQEMnndnmbVNZ1/AyOD7LNtJCGsDDHqbxg2APBqF39sfFGrn0+U7y5WWV
      d4/BwQnhowzH/T9EgZFtPCp1E4XLY0ECVph5mzfJdNkxStX4w2crMYxUAmu7k1JA+l8nymcYDRGrvJRSoRwRPVp0Ec/uB89n0K4VzsJnZZG64
      GYTZZ77Fg8hWL6Xi+/9B3Nb9ZUHuAK1126Xa2OKrfJzKv1vB3FZI40VUPgGo7Sh/ir4DjFYzDg4T5t5vjXOopJ4wzx7cOArRzfk1Ddp9dhxn6
      EXY+J6Z9pJ8NV2rQVonnd8kWNKb+2mlXc2blO6ibHsoJ5DEnD6t9BttR3tbr0vRi0nua6OyHReDKnbfMKiEGgDhX85i/YvQKgrtzrFIFrhhsK
      6AjbaQ1eyIMAY3iOeTkvNNGzDolgY=
  distributions: sdist bdist_wheel
  on:
    repo: thorgate/django-esteid
    tags: true
    python: "3.7"
    condition: "$DJANGO = 2.1"

notifications:
    email: false
